project:
  type: book

execute:
  freeze: auto

bibliography: [bibliography.bib]
book:
  title: "Introduction to R for BigCare 2024"
  reader-mode: true

  site-url: https://seandavi.github.io/2024-r-intro-bigcare/
  repo-url: https://github.com/seandavi/2024-r-intro-bigcare
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - part: Getting started
      chapters:
        - 010_rstudio_and_r.qmd
        - 020_r_basics.qmd
        - 030_r_functions.qmd
        - 045_loading_data.qmd
        - 050_r_scripts.qmd
        #- chatbots.qmd

    - part: Exploring data
      chapters:
        - eda.qmd
        - ggplot.qmd

    - part: data_structures_overview.qmd
      chapters:
        - vectors.qmd
        - matrices.qmd
        - dataframes_intro.qmd

    - part: Applications
      chapters:
        - 310_microbiome.qmd

format:
  html:
    code-tools: true
    fig-cap-location: margin
    tbl-cap-location: margin
    code-copy: true
    #code-fold: true
    theme:
      - flatly
      - style.scss
    #fontsize: "15px"
    #linestretch: 1.8
    #mainfont: "Roboto"
    #monofont: "Fira Mono"
    smooth-scroll: true
    toc-depth: 3
    code-link: true
    highlight-style: printing
    code-block-bg: true
    code-overflow: wrap
    reference-location: margin
    mermaid:
      theme: neutral
    css: styles.css
